# Generated by Django 6.0.6 on 2026-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('fav_subject', models.CharField(choices=[('Maths', 'Maths'), ('Phyics', 'Physics'), ('Chemistry', 'Chemistry'), ('Bio', 'Biology'), ('CS', 'Computer Science')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
